# Generated by Django 5.1.1 on 2024-09-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_article_last_price_change_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banck_name', models.CharField(max_length=150)),
                ('card_number', models.DecimalField(decimal_places=4, max_digits=16)),
                ('cvv2_number', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
        migrations.DeleteModel(
            name='PriceHistory',
        ),
    ]
