# Generated by Django 5.1.1 on 2024-09-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_payment_delete_pricehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_number',
            field=models.PositiveIntegerField(max_length=16),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cvv2_number',
            field=models.PositiveSmallIntegerField(max_length=5),
        ),
    ]
