# Generated by Django 5.1.1 on 2024-09-18 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_payment_card_number_alter_payment_cvv2_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
